### ISSUE TITLE
Release 3.4.0 checklist

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#1580]
Change external builds to tags

- [x] Forge
- [x] glbinding
- [x] clBLAS
- [x] clFFT
- [x] Boost.Compute

-------------------------------------

- [x] Update version number to 3.4.0
- [x] Update release notes
- [x] Update any licensing information

**Comment by shehzan10** [comment]
Checklist for v3.4.0 completed.
